backend:
  name: git-gateway
  branch: main # or master, depending on your repo

media_folder: "assets/uploads" # Where uploaded images will be stored
public_folder: "/assets/uploads"

collections:
  - name: "art"
    label: "Art"
    folder: "art"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
